services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:8080" # backend
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./symfony:/app/symfony
    depends_on:
      - symfony
    networks:
      - network

  symfony:
    container_name: symfony
    build:
      context: .
      dockerfile: ./docker/symfony/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./symfony:/app/symfony
    networks:
      - network

  mysql:
    container_name: database
    image: mysql:8
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "bookshop"
    networks:
      - network
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8070:80"
    depends_on:
      - mysql
    networks:
      - network

volumes:
  database:

networks:
  network:
    driver: bridge